name: Learn GitHub Actions
on:
  push:
    tags:
      - 'v*' # Specify the tag pattern that triggers this workflow (e.g., v1.0.0)
    branches:
      - main
  pull_request:
    types:
      - opened

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Bats
        run: npm install -g bats

      - name: Run Bats Version
        run: bats -v

  publish-release:
    runs-on: ubuntu-latest
    needs: check-bats-version
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            # Specify the files to include in the release
            path/to/your/artifact/file.jar
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Upload Release URL
        run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
        
      - name: Publish Release URL
        uses: actions/upload-artifact@v2
        with:
          name: release-url
          path: release_url.txt
